package com.mjd.erp.order;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-07-28T13:56:08.262-04:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "Order", 
                  wsdlLocation = "file:/home/pi/src/java/mule/order/Order.wsdl",
                  targetNamespace = "http://xmlns.example.com/1469188796440") 
public class Order extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://xmlns.example.com/1469188796440", "Order");
    public final static QName OrderServiceEndpoint1 = new QName("http://xmlns.example.com/1469188796440", "OrderServiceEndpoint1");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/pi/src/java/mule/order/Order.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Order.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/pi/src/java/mule/order/Order.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Order(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Order(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Order() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public Order(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public Order(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public Order(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns OrderService
     */
    @WebEndpoint(name = "OrderServiceEndpoint1")
    public OrderService getOrderServiceEndpoint1() {
        return super.getPort(OrderServiceEndpoint1, OrderService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OrderService
     */
    @WebEndpoint(name = "OrderServiceEndpoint1")
    public OrderService getOrderServiceEndpoint1(WebServiceFeature... features) {
        return super.getPort(OrderServiceEndpoint1, OrderService.class, features);
    }

}
