package com.mjd.erp.order;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-07-28T13:56:08.231-04:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://xmlns.example.com/1469188796440", name = "OrderService")
@XmlSeeAlso({com.mjd.erp.order.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface OrderService {

    @WebMethod(operationName = "Operation", action = "/Business/Services/Order/Order.serviceagent/OrderServiceEndpoint1/Operation")
    @WebResult(name = "OrderResponse", targetNamespace = "http://www.mjd.com/edi/Order/v1.0", partName = "response")
    public com.mjd.erp.order.OrderResponse operation(
        @WebParam(partName = "request", name = "OrderRequest", targetNamespace = "http://www.mjd.com/edi/Order/v1.0")
        com.mjd.erp.order.OrderRequest request
    ) throws OrderFault;
}
