
package com.mjd.erp.order;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-07-28T13:56:08.167-04:00
 * Generated source version: 3.1.6
 */

@WebFault(name = "ServiceSoapFault", targetNamespace = "http://www.mjd.com/edi/Order/v1.0")
public class OrderFault extends Exception {
    
    private com.mjd.erp.order.ServiceSoapFault serviceSoapFault;

    public OrderFault() {
        super();
    }
    
    public OrderFault(String message) {
        super(message);
    }
    
    public OrderFault(String message, Throwable cause) {
        super(message, cause);
    }

    public OrderFault(String message, com.mjd.erp.order.ServiceSoapFault serviceSoapFault) {
        super(message);
        this.serviceSoapFault = serviceSoapFault;
    }

    public OrderFault(String message, com.mjd.erp.order.ServiceSoapFault serviceSoapFault, Throwable cause) {
        super(message, cause);
        this.serviceSoapFault = serviceSoapFault;
    }

    public com.mjd.erp.order.ServiceSoapFault getFaultInfo() {
        return this.serviceSoapFault;
    }
}
